### ISSUE TITLE
docker exec backend python3 manage.py collectstatic not working on staging

### ISSUE THREAD

**Issue by nsiicm0** [highproformas-friends/curaSWISS#13]
docker exec backend python3 manage.py collectstatic

```
You have requested to collect static files at the destination
location as specified in your settings:

    /curaSWISS-backend/curaSWISS/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 184, in handle
    if input(''.join(message)) != 'yes':
EOFError: EOF when reading a line
```

**Comment by nsiicm0** [comment]
`docker exec backend python3 manage.py collectstatic --noinput`
seems to circumvent the error.
